const machines = [
  {
    "URN Alias": "CentOS",
    Publisher: "OpenLogic",
    Offer: "CentOS",
    SKU: 7.5,
    Version: "latest",
    URN: "OpenLogic:CentOS:7.5:latest",
  },
  {
    "URN Alias": "CentOS85Gen2",
    Publisher: "OpenLogic",
    Offer: "CentOS",
    SKU: "8_5-gen2",
    Version: "latest",
    URN: "OpenLogic:CentOS:8_5-gen2:latest",
  },
  {
    "URN Alias": "Debian",
    Publisher: "Debian",
    Offer: "debian-10",
    SKU: 10,
    Version: "latest",
    URN: "Debian:debian-10:10:latest",
  },
  {
    "URN Alias": "Debian11",
    Publisher: "Debian",
    Offer: "debian-11",
    SKU: "11-backports-gen2",
    Version: "latest",
    URN: "Debian:debian-11:11-backports-gen2:latest",
  },
  {
    "URN Alias": "Flatcar",
    Publisher: "kinvolk",
    Offer: "flatcar-container-linux-free",
    SKU: "stable",
    Version: "latest",
    URN: "kinvolk:flatcar-container-linux-free:stable:latest",
  },
  {
    "URN Alias": "FlatcarLinuxFreeGen2",
    Publisher: "kinvolk",
    Offer: "flatcar-container-linux-free",
    SKU: "stable-gen2",
    Version: "latest",
    URN: "kinvolk:flatcar-container-linux-free:stable-gen2:latest",
  },
  {
    "URN Alias": "openSUSE-Leap",
    Publisher: "SUSE",
    Offer: "opensuse-leap-15-3",
    SKU: "gen2",
    Version: "latest",
    URN: "SUSE:opensuse-leap-15-3:gen2:latest",
  },
  {
    "URN Alias": "OpenSuseLeap154Gen2",
    Publisher: "SUSE",
    Offer: "openSUSE-leap-15-4",
    SKU: "gen2",
    Version: "latest",
    URN: "SUSE:openSUSE-leap-15-4:gen2:latest",
  },
  {
    "URN Alias": "RHEL",
    Publisher: "RedHat",
    Offer: "RHEL",
    SKU: "7-LVM",
    Version: "latest",
    URN: "RedHat:RHEL:7-LVM:latest",
  },
  {
    "URN Alias": "RHELRaw8LVMGen2",
    Publisher: "RedHat",
    Offer: "RHEL",
    SKU: "8-lvm-gen2",
    Version: "latest",
    URN: "RedHat:RHEL:8-lvm-gen2:latest",
  },
  {
    "URN Alias": "SLES",
    Publisher: "SUSE",
    Offer: "sles-15-sp3",
    SKU: "gen2",
    Version: "latest",
    URN: "SUSE:sles-15-sp3:gen2:latest",
  },
  {
    "URN Alias": "SuseSles15SP3",
    Publisher: "SUSE",
    Offer: "sles-15-sp3",
    SKU: "gen2",
    Version: "latest",
    URN: "SUSE:sles-15-sp3:gen2:latest",
  },
  {
    "URN Alias": "UbuntuLTS",
    Publisher: "Canonical",
    Offer: "UbuntuServer",
    SKU: "18.04-LTS",
    Version: "latest",
    URN: "Canonical:UbuntuServer:18.04-LTS:latest",
  },
  {
    "URN Alias": "Ubuntu2204",
    Publisher: "Canonical",
    Offer: "0001-com-ubuntu-server-jammy",
    SKU: "22_04-lts-gen2",
    Version: "latest",
    URN: "Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest",
  },
  {
    "URN Alias": "Win2022Datacenter",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2022-Datacenter",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2022-Datacenter:latest",
  },
  {
    "URN Alias": "Win2022AzureEditionCore",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2022-datacenter-azure-edition-core",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition-core:latest",
  },
  {
    "URN Alias": "Win2019Datacenter",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2019-Datacenter",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest",
  },
  {
    "URN Alias": "Win2016Datacenter",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2016-Datacenter",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest",
  },
  {
    "URN Alias": "Win2012R2Datacenter",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2012-R2-Datacenter",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest",
  },
  {
    "URN Alias": "Win2012Datacenter",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2012-Datacenter",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2012-Datacenter:latest",
  },
  {
    "URN Alias": "Win2008R2SP1",
    Publisher: "MicrosoftWindowsServer",
    Offer: "WindowsServer",
    SKU: "2008-R2-SP1",
    Version: "latest",
    URN: "MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:latest",
  },
];
