"use client";

import { AuthContext, AuthContextProvider } from "@/context/AuthContext";
import { RessourceContextProvider } from "@/context/RessourceContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Inter } from "next/font/google";
import { useContext } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const context = useContext(AuthContext);
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <AuthContextProvider>
            <RessourceContextProvider>{children}</RessourceContextProvider>
          </AuthContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
